// The words the page shows, in English and in Portuguese (Portugal).
// The English text is the key: tr('Add event'), tr('weeks {0}–{1}', from, to). The words of the plan
// files (race, build, not-done) are not translated: they are the file format.

export const LANGS = ['en', 'pt'];
let lang = 'en';

export function setLang(l) { lang = LANGS.includes(l) ? l : 'en'; }
export function getLang() { return lang; }

// the text in the language in use, with {0}, {1}… filled in; a text with no translation stays in English
export function tr(text, ...args) {
  const s = lang === 'pt' && Object.prototype.hasOwnProperty.call(PT, text) ? PT[text] : text;
  return args.length ? s.replace(/\{(\d)\}/g, (m, i) => args[+i] === undefined ? m : args[+i]) : s;
}

// a number as written in the language in use: 5.9, or 5,9 in Portuguese
export function dec(x, digits) {
  const s = digits === undefined ? String(x) : x.toFixed(digits);
  return lang === 'pt' ? s.replace('.', ',') : s;
}

export const PT = {
  // the header and the status line
  "Plan": "Plano",
  "Events": "Eventos",
  "Today": "Hoje",
  "Saving…": "A guardar…",
  "{0} problem": "{0} problema",
  "{0} problems": "{0} problemas",
  "Problems": "Problemas",
  "None": "Nenhum",
  "error": "erro",
  "warning": "aviso",
  "Close": "Fechar",
  "The plan cannot be read: is the server running?": "Não foi possível ler o plano: o servidor está ligado?",
  "Not saved yet: is the server running?": "Ainda não foi guardado: o servidor está ligado?",
  "The plan cannot be read: is there a connection?": "Não foi possível ler o plano: há ligação à internet?",
  "Not saved yet: is there a connection?": "Ainda não foi guardado: há ligação à internet?",
  "No sessions": "Sem sessões",
  "Next session": "Próxima sessão",
  "Previous day": "Dia anterior",
  "Next day": "Dia seguinte",
  "Full page": "Página completa",
  "Repository": "Repositório",
  "Folder": "Pasta",
  "Token": "Token",
  "Open": "Abrir",
  "Write the repository as owner/name": "Escreva o repositório como dono/nome",
  "GitHub refused the token": "O GitHub recusou o token",
  "The repository or the folder was not found with this token": "O repositório ou a pasta não foram encontrados com este token",
  "The plan changed on disk; your last change was not saved": "O plano mudou no disco; a última alteração não foi guardada",
  "{0} has a problem; fix it in the file first": "{0} tem um problema; corrija-o primeiro no ficheiro",
  // the annual sheet
  "Month": "Mês",
  "Monday": "Segunda",
  "Races": "Provas",
  "Macrocycle": "Macrociclo",
  "Mesocycle": "Mesociclo",
  "Content": "Conteúdo",
  "Microcycle": "Microciclo",
  "Type": "Tipo",
  "Load %": "Carga %",
  "Km": "Km",
  "Sessions": "Sessões",
  "Season": "Época",
  "Week {0}": "Semana {0}",
  "week {0}": "semana {0}",
  "weeks {0}–{1}": "semanas {0}–{1}",
  "Week {0} type": "Tipo da semana {0}",
  "Set by hand": "Definido à mão",
  "Week {0} load not set": "Semana {0}: carga por definir",
  "Week {0} load {1} percent": "Semana {0}: carga {1} por cento",
  "estimate {0} km ({1}), sessions {2} km": "estimativa {0} km ({1}), sessões {2} km",
  "load {0}% × content {1}": "carga {0}% × conteúdo {1}",
  "not planned yet: an average week": "ainda por planear: uma semana média",
  "sessions {0} km": "sessões {0} km",
  "{0}: {1} km this season, {2} km a year recommended": "{0}: {1} km esta época, {2} km por ano recomendados",
  "Season: {0} km done, {1} km planned": "Época: {0} km feitos, {1} km planeados",
  "of {0} km a year": "de {0} km por ano",
  "Weeks that have ended: {0} of {1} km estimated": "Semanas terminadas: {0} de {1} km estimados",
  "{0} session of {1}": "{0} sessão de {1}",
  "{0} sessions of {1}": "{0} sessões de {1}",
  "{0} of {1} together": "{0} de {1} em conjunto",
  "develop {0}, maintain {1}": "desenvolver {0}, manter {1}",
  "not suggested at this age": "não sugerido neste escalão",
  "developing": "a desenvolver",
  "maintaining": "a manter",
  "below maintenance": "abaixo da manutenção",
  "trained": "treinado",
  "absent": "ausente",
  // microcycle types and load patterns (the course's names)
  "Introductory": "Introdutório",
  "Load": "Carga",
  "Shock": "Choque",
  "Recovery": "Recuperação",
  "Activation": "Ativação",
  "Competition": "Competição",
  "Build: load, shock, recovery": "Desenvolvimento: carga, choque, recuperação",
  "Introduction, then build": "Introdução, depois desenvolvimento",
  "Recovery, then build": "Recuperação, depois desenvolvimento",
  "Competition: load, activation, race": "Competição: carga, ativação, prova",
  "Recovery only": "Só recuperação",
  "Not planned": "Por planear",
  "Microcycle types": "Tipos de microciclo",
  "Prepares for the next level of load or the next mesocycle, with reduced load.": "Prepara para o nível de carga seguinte ou para o mesociclo seguinte, com carga reduzida.",
  "Enough volume to improve, without exhausting the athlete.": "Volume suficiente para melhorar, sem esgotar o atleta.",
  "The highest stimulus: development sessions without full recovery between them.": "O estímulo máximo: sessões de desenvolvimento sem recuperação completa entre elas.",
  "Regeneration: low volume and intensity.": "Regeneração: volume e intensidade baixos.",
  "Before an important race: full recovery, low volume, high intensity, modelling the race.": "Antes de uma prova importante: recuperação completa, volume baixo, intensidade alta, simulação da prova.",
  "The race week: the race, supplementary sessions and recovery.": "A semana da prova: a prova, sessões complementares e recuperação.",
  // the cycle panels
  "Name": "Nome",
  "Load pattern": "Padrão de carga",
  "Move earlier": "Mais cedo",
  "Move later": "Mais tarde",
  "Split": "Dividir",
  "new block from": "novo bloco a partir da",
  "new macrocycle from": "novo macrociclo a partir da",
  "Start new macrocycle here": "Começar novo macrociclo aqui",
  "Merge into previous": "Juntar ao anterior",
  "Delete": "Apagar",
  "New block": "Novo bloco",
  "New macrocycle": "Novo macrociclo",
  // the week and the session
  "Pattern": "Padrão",
  "{0} of {1} km": "{0} de {1} km",
  "{0} off the water": "{0} fora de água",
  "Previous week": "Semana anterior",
  "Next week": "Semana seguinte",
  "Add session": "Adicionar sessão",
  "AM": "Manhã",
  "PM": "Tarde",
  "Session": "Sessão",
  "Main zone": "Zona principal",
  "No zone found": "Nenhuma zona encontrada",
  "no zone": "sem zona",
  "Notes": "Notas",
  "Place": "Local",
  "Not done": "Não realizada",
  "not done": "não realizada",
  "Delete session": "Apagar sessão",
  "Empty session": "Sessão vazia",
  "Water": "Água",
  "Pool": "Piscina",
  "Gym": "Ginásio",
  "Land": "Terra",
  // races and events
  "Add event": "Adicionar evento",
  "New event": "Novo evento",
  "Date": "Data",
  "Until": "Até",
  "Confirmed": "Confirmada",
  "Kind": "Tipo",
  "Race type": "Tipo de prova",
  "Boats": "Embarcações",
  "Date confirmed": "Data confirmada",
  "{0} importance": "Importância para {0}",
  "importance {0} of 3": "importância {0} de 3",
  "date confirmed": "data confirmada",
  "date not confirmed": "data por confirmar",
  "Race": "Prova",
  "Test": "Controlo",
  "Camp": "Estágio",
  "Holiday": "Férias",
  "No water": "Sem água",
  "Sprint": "Sprint",
  "Fundo": "Fundo",
  "Maratona": "Maratona",
  "Solo": "Individual",
  "Tripulações": "Tripulações",
  "Mixed": "Ambos",
  // months and days
  "Jan": "Jan",
  "Feb": "Fev",
  "Mar": "Mar",
  "Apr": "Abr",
  "May": "Mai",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Ago",
  "Sep": "Set",
  "Oct": "Out",
  "Nov": "Nov",
  "Dec": "Dez",
  "Mon": "Seg",
  "Tue": "Ter",
  "Wed": "Qua",
  "Thu": "Qui",
  "Fri": "Sex",
  "Sat": "Sáb",
  "Sun": "Dom",
  // why an edit was refused
  "weeks that have ended cannot be moved": "as semanas que já terminaram não podem ser movidas",
  "no such mesocycle": "esse mesociclo não existe",
  "no such macrocycle": "esse macrociclo não existe",
  "whole weeks only": "só semanas inteiras",
  "a block needs at least one week": "um bloco precisa de pelo menos uma semana",
  "the new block must start inside the block": "o novo bloco tem de começar dentro do bloco",
  "the last block cannot be deleted": "o último bloco não pode ser apagado",
  "there is no block on that side": "não há bloco desse lado",
  "this block already starts a macrocycle": "este bloco já começa um macrociclo",
  "the new macrocycle must start inside the macrocycle": "o novo macrociclo tem de começar dentro do macrociclo",
  "there is no previous macrocycle": "não há macrociclo anterior",
  "a block needs a name": "um bloco precisa de um nome",
  "a macrocycle needs a name": "um macrociclo precisa de um nome",
  "unknown load pattern": "padrão de carga desconhecido",
  "unknown zone {0}": "zona desconhecida: {0}",
  "there is no week type \"{0}\"": "não existe o tipo de semana \"{0}\"",
  "load is a whole number from 0 to 100": "a carga é um número inteiro de 0 a 100",
  "a session needs a date": "uma sessão precisa de uma data",
  "a session is in the morning (am) or the afternoon (pm)": "uma sessão é de manhã (am) ou de tarde (pm)",
  "plan {0} has no band \"{1}\"": "o plano {0} não tem o escalão \"{1}\"",
  "a session is on the water, or in the pool, the gym or on land": "uma sessão é na água, na piscina, no ginásio ou em terra",
  "an event needs a date": "um evento precisa de uma data",
  "an event needs a name": "um evento precisa de um nome",
  "until is a date": "«até» é uma data",
  "an event cannot end before it starts": "um evento não pode acabar antes de começar",
  "unknown kind of event": "tipo de evento desconhecido",
  "only races have a type: {0}": "só as provas têm tipo: {0}",
  "only races have boats: {0}": "só as provas têm embarcações: {0}",
  "there is no plan \"{0}\"": "não existe o plano \"{0}\"",
  "importance is 1, 2 or 3": "a importância é 1, 2 ou 3",
  "only races have an importance": "só as provas têm importância",
  "an event applies to at least one plan": "um evento aplica-se a pelo menos um plano",
  // problems found by check (the words in « » are the file's own)
  "the file is missing": "o ficheiro não existe",
  "plans lists \"{0}\", which has no folder in plans/": "«plans» indica \"{0}\", que não tem pasta em plans/",
  "load is missing for week type {0}": "falta «load» para o tipo de semana {0}",
  "reference is missing for {0}": "falta «reference» para {0}",
  "pace default is missing for {0}": "falta «pace default» para {0}",
  "hard is missing for {0}": "falta «hard» para {0}",
  "race is missing for {0}": "falta «race» para {0}",
  "warmup is missing": "falta «warmup»",
  "develop and maintain must list the same contents; only one has {0}": "«develop» e «maintain» têm de indicar os mesmos conteúdos; só um tem {0}",
  "develop lists {0} in two contents": "«develop» indica {0} em dois conteúdos",
  "yearly km are given for \"{0}\", which is not a band of any plan": "há km anuais para \"{0}\", que não é escalão de nenhum plano",
  "zone-km is given for \"{0}\", which is not a band of any plan": "há «zone-km» para \"{0}\", que não é escalão de nenhum plano",
  "zones are given for \"{0}\", which is not a band of any plan": "há zonas para \"{0}\", que não é escalão de nenhum plano",
  "{0} ({1}) is outside the season": "{0} ({1}) está fora da época",
  "{0} is in no plan": "{0} não está em nenhum plano",
  "{0} ({1}) is in the past and its date was never confirmed": "{0} ({1}) já passou e a data nunca foi confirmada",
  "the mesocycles cover {0} weeks and the season has {1}": "os mesociclos cobrem {0} semanas e a época tem {1}",
  "{0} is not the Monday of a week in the season": "{0} não é a segunda-feira de uma semana da época",
  "there is no week type \"{0}\" in tables.txt": "não existe o tipo de semana \"{0}\" em tables.txt",
  "there are two sessions for {0}": "há duas sessões para {0}",
  "{0} is outside the season": "{0} está fora da época",
  // what the course would question about a session and a week
  "{0}: not recommended for {1}": "{0}: não recomendado para {1}",
  "{0} after {1}: the recommended order is R5 and R6, then R3, R3+ and R4, then R2 and R1": "{0} depois de {1}: a ordem recomendada é R5 e R6, depois R3, R3+ e R4, e por fim R2 e R1",
  "{0}: {1} exceeds the recommended maximum of {2} to {3}": "{0}: {1} ultrapassa máximo recomendado de {2} a {3}",
  "{0}: {1} is below the recommended minimum of {2} to {3}": "{0}: {1} abaixo do mínimo recomendado de {2} a {3}",
  "{0}: {1} of rest, below the recommended minimum of {2}": "{0}: {1} de recuperação, abaixo do mínimo recomendado de {2}",
  "{0}: {1} of rest after {2}, below the recommended minimum of 1:{3}": "{0}: {1} de recuperação após {2}, abaixo do mínimo recomendado de 1:{3}",
  "{0}: {1} in one session exceeds the recommended maximum of {2}": "{0}: {1} numa sessão ultrapassa máximo recomendado de {2}",
  "{0} starts {1} into the session: at least {2} before it is recommended": "{0} começa aos {1} da sessão: recomenda-se pelo menos {2} antes",
  "{0} before {1}: the quality session is recommended in the morning": "{0} antes de {1}: recomenda-se a sessão de qualidade de manhã",
  "{0} R7 sessions exceed the recommended maximum of {1} a week in the competitive period": "{0} sessões de R7 ultrapassam máximo recomendado de {1} por semana no período competitivo",
  "{0} R7 sessions exceed the recommended maximum of {1} a week in the preparatory period": "{0} sessões de R7 ultrapassam máximo recomendado de {1} por semana no período preparatório",
  "A recovery week with {0}: low volume and intensity are recommended": "Semana de recuperação com {0}: recomenda-se volume e intensidade baixos",
  "{0} is the day before {1}: a light day is recommended": "{0} é na véspera de {1}: recomenda-se um dia leve",
  "{0} is the day after {1}: a day off is recommended": "{0} é o dia a seguir a {1}: recomenda-se dia livre",
  "{0} sessions, {1} the week before: in the taper, lower the volume and keep the number of sessions": "{0} sessões, {1} na semana anterior: no taper, baixar o volume e manter o número de sessões",
  "{0} and {1} are less than {2} h apart": "{0} e {1} têm menos de {2} h de intervalo",
  "{0} is the block's content and has no session this week": "{0} é conteúdo do bloco e não tem nenhuma sessão esta semana",
  // the zone cards: labels
  "Intensity": "Intensidade",
  "How to train": "Como treinar",
  "Per week": "Por semana",
  "Builds": "Desenvolve-se",
  "Decays": "Perde-se",
  "Ages": "Escalões",
  "Develop: {0} sessions. Maintain: {1}.": "Desenvolver: {0} sessões. Manter: {1}.",
  "Counted together with {0}.": "Contado em conjunto com {0}.",
  "Recovery after a session: {0}.": "Recuperação depois de uma sessão: {0}.",
  "No counts given.": "Sem valores.",
  // the zone cards: the course's text, in its own words where the slides have them (slides 135–146, 166, 188)
  "Aerobic, lipid": "Aeróbio lipídico",
  "The lowest speed that still improves aerobic endurance. Builds paddling economy, teaches the body to burn fat and spare glycogen, and speeds up recovery after hard work.": "A velocidade mínima que ainda melhora a resistência aeróbia. Desenvolve a economia de pagaiada, aumenta a capacidade de usar gorduras e poupar glicogénio, e acelera a recuperação de tarefas intensas.",
  "Continuous or split paddling, up to 120'": "Método contínuo ou fracionado, até 120'",
  "A good zone for technique work": "Bom ritmo para trabalho técnico",
  "Negligible risk of overtraining": "Risco negligenciável de excesso de treino",
  "From Iniciado.": "A partir de Iniciado.",
  "Continuous and interval methods": "Métodos contínuos e intervalados",
  "About 60' of work per session (after 45', about 60% of glycogen is used)": "Cerca de 60' de trabalho por sessão (aos 45', cerca de 60% do glicogénio está gasto)",
  "For sprinters: no excessive volume, split work, add high-intensity sets": "Para velocistas: sem volumes excessivos, trabalho fracionado, incluir séries de alta intensidade",
  "Aerobic capacity": "Capacidade aeróbia",
  "A pace close to VO2max. Trains how long VO2max can be held.": "Um ritmo próximo do VO2max. Treina o tempo que se consegue manter o VO2max.",
  "Reps of 2'–6' (around 1500 m for interval work)": "Repetições de 2'–6' (cerca de 1500 m em trabalho intervalado)",
  "About 30' of work per session": "Cerca de 30' de trabalho por sessão",
  "Active recovery, work to rest about 1:1": "Recuperação ativa, relação trabalho:descanso de cerca de 1:1",
  "Warm up well: full VO2max is only available after 30'–50' of activity": "Aquecer bem: o VO2max a 100% só está disponível após 30'–50' de atividade",
  "Develop it fully before starting anaerobic work": "Desenvolver ao máximo antes de começar o trabalho anaeróbio",
  "Aerobic power (VO2max)": "Potência aeróbia (VO2max)",
  "Work at VO2max. 100% of VO2max can only be held for a few minutes (4'–7').": "Trabalho ao VO2max. 100% do VO2max só é possível durante alguns minutos (4'–7').",
  "Reps of 2'–3' (around 800 m)": "Repetições de 2'–3' (cerca de 800 m)",
  "About 15' of work per session": "Cerca de 15' de trabalho por sessão",
  "Active recovery, work to rest 1:1, up to 1:3 for shorter reps": "Recuperação ativa, relação 1:1, até 1:3 em repetições mais curtas",
  "Intermittent option: 30'' at 95–105% of max aerobic speed, 10''–20'' easy": "Opção intermitente: 30'' a 95–105% da VAM, 10''–20'' de recuperação",
  "The shorter the rep, the closer it gets to R4": "Quanto mais curta a repetição, mais perto do R4",
  "Lactic capacity (tolerance)": "Capacidade láctica (tolerância)",
  "Working with high lactate for as long as possible. Trains tolerance of discomfort and holding technique under fatigue.": "Trabalhar com altas concentrações de lactato pelo maior tempo possível. Treina a tolerância ao desconforto e a manutenção da técnica em fadiga.",
  "Efforts of about 75''–80''": "Esforços de cerca de 75''–80''",
  "Repetitions of 100–400 m, rest 1:3 or more": "Repetições de 100–400 m, recuperação 1:3 ou mais",
  "Or series of 300–600 m with 10''–30'' rest and 3'–8' between sets": "Ou séries de 300–600 m com 10''–30'' de recuperação e 3'–8' entre séries",
  "Active recovery": "Recuperação ativa",
  "Watch glycogen stores; these sessions cause a lot of fatigue": "Controlar as reservas de glicogénio; estas sessões causam muita fadiga",
  "Lactic power": "Potência láctica",
  "The highest rate of energy from anaerobic glycolysis. Trains holding technique at very high intensity.": "A taxa máxima de produção de energia pela glicólise anaeróbia. Treina a manutenção da técnica em alta intensidade.",
  "Efforts of about 45''": "Esforços de cerca de 45''",
  "Repetitions of 100–200 m, or split series of 50–100 m": "Repetições de 100–200 m, ou séries fracionadas de 50–100 m",
  "3'–6' recovery, active, long enough to restore the fuel": "3'–6' de recuperação ativa, o suficiente para repor os substratos",
  "About 1000 m of work per session": "Cerca de 1000 m de trabalho por sessão",
  "Do it fresh, with minimal fatigue": "Executar num estado mínimo de fadiga",
  "Alactic (speed)": "Aláctico (velocidade)",
  "Maximal speed. R6+ is alactic power: acceleration and top speed, 4''–10''. R6 is alactic capacity: resisting the loss of speed, 10''–20''.": "Velocidade máxima. R6+ é potência aláctica: aceleração e velocidade máxima, 4''–10''. R6 é capacidade aláctica: resistir à perda de velocidade, 10''–20''.",
  "Only when fresh; the number of reps is set by quality": "Só sem fadiga; o número de repetições depende da qualidade",
  "Rest must restore full work capacity, but long passive rests cool the muscles": "As pausas devem repor toda a capacidade de trabalho, mas recuperações passivas e longas arrefecem os músculos",
  "Vary the tasks; monotony and too much volume lower the intensity": "Variar as tarefas; a monotonia e o volume excessivo baixam a intensidade",
  "Competition pace": "Ritmo de competição",
  "Racing efficiently: the pace, tactics and conditions of the event.": "Competir com eficiência: o ritmo, a tática e as condições da prova.",
  "Race speed for the target distance": "Velocidade de prova para a distância-alvo",
  "USRPT: 15'' on, 15'' off at race speed; stop when the pace is lost": "USRPT: 15'' de trabalho, 15'' de descanso à velocidade de prova; parar quando se perde o ritmo",
  "At most 2 sessions per microcycle in preparation, 4 in the competitive period.": "No máximo 2 sessões por microciclo no período preparatório, 4 no período competitivo.",
  "Kinds of work": "Tipos de trabalho",
  "In a session": "Na sessão",
  "In the season": "Na época",
  "Resisted": "Com travão",
  "Km a year": "Km por ano",
  "Kayak 60–70 strokes/min, canoe 36–42": "Kayak 60–70 pagaiadas/min, canoa 36–42",
  "For sprinters: moderate distances that keep the technique, with a high-intensity set": "Para velocistas: distâncias moderadas que garantam a qualidade técnica, com uma série de alta intensidade",
  "With other contents it usually goes at the end, as regeneration. As the main content it goes with R6, resisted work and hypertrophy strength.": "Junto com outros conteúdos vai geralmente no final, como regeneração. Como conteúdo principal combina com R6, trabalho com travão e força de hipertrofia.",
  "Basic phase, for every race distance.": "Fase básica, para todas as distâncias de prova.",
  "Aerobic glycolytic": "Aeróbio glicolítico",
  "The aerobic–anaerobic transition zone: the highest steady speed that does not accumulate lactate. The base of aerobic work.": "A zona de transição aeróbia-anaeróbia: a velocidade constante mais alta que não acumula lactato. A base do trabalho aeróbio.",
  "Kayak 70–80 strokes/min, canoe 42–48": "Kayak 70–80 pagaiadas/min, canoa 42–48",
  "Usually at the end of the session, after anaerobic work. As the main content it goes with R6, resisted work and hypertrophy strength.": "Geralmente no final da sessão, depois do trabalho anaeróbio. Como conteúdo principal combina com R6, trabalho com travão e força de hipertrofia.",
  "Kayak 80–90 strokes/min, canoe 48–54": "Kayak 80–90 pagaiadas/min, canoa 48–54",
  "In the middle of the session, after speed and before R2 and R1. It goes with a main content of R4 or R5.": "A meio da sessão, depois da velocidade e antes de R2 e R1. Combina com um conteúdo principal de R4 ou R5.",
  "Specific phase for 500 m and 1000 m; competitive phase for 1000 m.": "Fase específica para 500 m e 1000 m; fase competitiva para 1000 m.",
  "Kayak 90–100 strokes/min, canoe 54–60": "Kayak 90–100 pagaiadas/min, canoa 54–60",
  "100% VO2max · 100% HRmax": "100% VO2max · 100% FC máx",
  "Basic phase for 200 m. Specific phase for 500 m and 1000 m, where it is the key content. Competitive phase for 500 m and 1000 m.": "Fase básica para 200 m. Fase específica para 500 m e 1000 m, onde é o conteúdo-chave. Fase competitiva para 500 m e 1000 m.",
  "Kayak 110–120 strokes/min, canoe 66–72": "Kayak 110–120 pagaiadas/min, canoa 66–72",
  "In the middle of the session. As the main content, with R5, it goes with resisted work, R3 and R3+. A heavy lactic load before aerobic or speed work works against them.": "A meio da sessão. Como conteúdo principal, com R5, combina com trabalho com travão, R3 e R3+. Uma carga láctica pesada antes de trabalho aeróbio ou de velocidade prejudica-os.",
  "Specific and competitive phases for every distance; a key content of the specific phase for 500 m. It comes after R3+ and before speed.": "Fases específica e competitiva para todas as distâncias; conteúdo-chave da fase específica para 500 m. Vem depois de R3+ e antes da velocidade.",
  "Maximal stroke rate": "Frequência de pagaiada máxima",
  "Maximal lactate": "Lactato máximo",
  "First in the session, done fresh, with R6. As the main content, with R4, it goes with resisted work, R3 and R3+.": "Primeiro na sessão, sem fadiga, com R6. Como conteúdo principal, com R4, combina com trabalho com travão, R3 e R3+.",
  "200 m: specific phase, where it is the key content, and competitive phase. 500 m: specific and competitive phases. 1000 m: specific phase only.": "200 m: fase específica, onde é o conteúdo-chave, e fase competitiva. 500 m: fases específica e competitiva. 1000 m: só fase específica.",
  "Below 90% of top speed the stimulus is too weak": "Abaixo de 90% da velocidade máxima o estímulo é insuficiente",
  "Acceleration: 5''–10'' of work": "Capacidade de aceleração: 5''–10'' de trabalho",
  "Top speed: about 10''": "Velocidade máxima: cerca de 10''",
  "Speed endurance: 10''–20''": "Resistência à velocidade máxima: 10''–20''",
  "Each with 3'–4' of recovery, and 1'–3' of work in the session": "Cada uma com 3'–4' de recuperação, e 1'–3' de trabalho na sessão",
  "First in the session, done fresh. As the main content it goes with R1, R2, explosive strength and hypertrophy strength. Speed before aerobic or lactic work helps them.": "Primeiro na sessão, sem fadiga. Como conteúdo principal combina com R1, R2, força explosiva e força de hipertrofia. Velocidade antes de trabalho aeróbio ou láctico ajuda-os.",
  "200 m: R6+ in the basic phase, R6 in the specific and competitive phases. 500 m: R6+ in the basic phase, R6 in the specific phase. 1000 m: R6 in the specific phase.": "200 m: R6+ na fase básica, R6 nas fases específica e competitiva. 500 m: R6+ na fase básica, R6 na fase específica. 1000 m: R6 na fase específica.",
  "A faster first part suits athletes with good aerobic capacity who do not build lactate fast": "Uma primeira parte mais rápida serve atletas com boa capacidade aeróbia que não acumulam lactato depressa",
  "A faster second part suits athletes of low aerobic capacity who build lactate fast": "Uma segunda parte mais rápida serve atletas de baixa capacidade aeróbia que acumulam lactato depressa",
  "Fewer of the hardest simulation sets, more of the easier ones": "Menos séries de simulação das mais difíceis, mais das mais fáceis",
  "Endurance pace: pieces of 20% of the race distance, 15''–1' between parts, more than 8'–10' between pieces": "Int. resistência: partes de 20% da distância de competição, 15''–1' entre partes, mais de 8'–10' entre séries",
  "Broken series: the race distance in equal parts, 10''–1' between parts, more than 10'–15' between pieces": "Séries fracionadas: a distância de competição em partes iguais, 10''–1' entre partes, mais de 10'–15' entre séries",
  "Simulation series: the race distance in unequal parts, 10''–90'' between parts, more than 10' between pieces": "Séries simuladoras: a distância de competição com parciais diferentes, 10''–90'' entre partes, mais de 10' entre séries",
  "Speed pace: pieces of 2/3 of the race distance, more than 8'–15' between pieces": "Int. velocidade: partes de 2/3 da distância de competição, mais de 8'–15' entre séries",
  "2–6 race distances in the session (2–4 for speed pace)": "2–6 distâncias de competição na sessão (2–4 em int. velocidade)",
  "Warm up to race readiness before any race-pace session.": "Ativar até estar pronto para competir antes de qualquer sessão de ritmo de competição.",
  "The third and last part of a preparation: simulating the competition. In the taper, work at race speed with full recovery.": "A terceira e última parte de uma preparação: simular a competição. No taper, trabalho à velocidade de prova com recuperação total.",
  "65–75% VO2max · 70–80% HRmax": "65–75% VO2max · 70–80% FC máx",
  "Lactate 1–2 mmol/L · RPE 10–11": "Lactato 1–2 mmol/L · RPE 10–11",
  "75–85% VO2max · 80–90% HRmax": "75–85% VO2max · 80–90% FC máx",
  "Lactate 2–4 mmol/L · RPE 12–14": "Lactato 2–4 mmol/L · RPE 12–14",
  "90–95% VO2max · 95–98% HRmax": "90–95% VO2max · 95–98% FC máx",
  "Lactate 4–6 mmol/L · RPE 15–16": "Lactato 4–6 mmol/L · RPE 15–16",
  "Lactate 6–8 mmol/L · RPE 17–19": "Lactato 6–8 mmol/L · RPE 17–19",
  "105–120% VO2max": "105–120% VO2max",
  "Lactate 8–14 mmol/L": "Lactato 8–14 mmol/L",
  "120–140% VO2max": "120–140% VO2max",
  "Above 160% VO2max": "Acima de 160% VO2max",
  "Repetitions of 3'–8', 1' between them, 3' between sets": "Repetições de 3'–8', 1' entre elas, 3' entre séries",
  "At least 8 weeks.": "Pelo menos 8 semanas.",
  "4–6 weeks, at 3 sessions a week.": "4–6 semanas, com 3 sessões por semana.",
  "Trained all season.": "Treina-se toda a época.",
  "Used as races approach.": "Usado com a aproximação das provas.",
  "About 30 ± 5 days without training.": "Cerca de 30 ± 5 dias sem treino.",
  "About 18 ± 4 days without training.": "Cerca de 18 ± 4 dias sem treino.",
  "About 5 ± 3 days without training.": "Cerca de 5 ± 3 dias sem treino.",
  "From Infantil.": "A partir de Infantil.",
  "From Cadete.": "A partir de Cadete.",
  "Seniors only.": "Só Seniores.",
  "From Junior.": "A partir de Júnior.",
  "R1F: R1 against a brake. Develops with 3–4 sessions a week, maintained with 2. Counted here as R1.": "R1F: R1 com travão. Desenvolve-se com 3–4 sessões por semana, mantém-se com 2. Aqui conta como R1.",
  "R2F: R2 against a brake. R2+: between R2 and R3, the repetitions of R2 with 30'' of rest. Both are counted here as R2.": "R2F: R2 com travão. R2+: entre R2 e R3, as repetições de R2 com 30'' de recuperação. Aqui contam ambos como R2.",
  "R3F: R3 against a brake. Develops with 2–4 sessions a week, maintained with 1. Counted here as R3.": "R3F: R3 com travão. Desenvolve-se com 2–4 sessões por semana, mantém-se com 1. Aqui conta como R3.",
  "R3+F: R3+ against a brake. Counted here as R3+.": "R3+F: R3+ com travão. Aqui conta como R3+.",
  "R4F: R4 against a brake. Counted here as R4.": "R4F: R4 com travão. Aqui conta como R4.",
  "R5F: R5 against a brake. Counted here as R5.": "R5F: R5 com travão. Aqui conta como R5.",
  "R6F: R6 against a brake. Develops with 2–4 sessions a week, maintained with 1–2. R6F and R6+ are counted here as R6.": "R6F: R6 com travão. Desenvolve-se com 2–4 sessões por semana, mantém-se com 1–2. Aqui R6F e R6+ contam como R6."
};
